{
 "title": "dashboard_opstelling",
 "time": { "from": "2023-02-05T22:00:00.000Z", "to": "2023-02-12T22:00:00.000Z" },
 "panels": [
  {
   "title": "Phone history",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "240s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "historyphone",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "laptop history",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "240s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "historylaptop",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "box history",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "240s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "historybox",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pc history",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "240s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "historypc",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}